import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <div className="flex items-center  justify-between space-x-5">
          <a href="/" className="">
            Kihyeon Kwon
          </a>
          <div>
            <a href="/tailwind" className="mylink">
              Tailwind.css
            </a>
            <a href="/next" className="mylink">
              Next.js
            </a>
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
